version: 2

sources:
  - name: bronze
    schema: bronze
    description: "Bronze (raw landing) tables loaded from CSV ingestion."

    tables:
      # -----------------------
      # Ingestion audit tables
      # -----------------------
      - name: ingestion_files
        description: "File-level ingestion audit metadata (one row per dataset load)."
        columns:
          - name: batch_id
            tests: [not_null]
          - name: dataset_name
            tests:
              - not_null
              - accepted_values:
                  values: ["drivers", "offers", "bookings"]
          - name: source_uri
            tests: [not_null]
          - name: file_format
            tests:
              - accepted_values:
                  values: ["csv"]
          - name: file_md5
            description: " "
            # tests: [not_null]
          - name: rows_loaded
            tests:
              - not_null
          - name: load_started_at
            tests: [not_null]
          - name: load_finished_at
          - name: load_status
            tests:
              - not_null
              - accepted_values:
                  values: ["SUCCESS", "FAILED"]
          - name: error_message
          - name: created_at
            tests: [not_null]

        tests:
          # Ensure 1 record per dataset per batch (tightest useful uniqueness)
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns: ["batch_id", "dataset_name", "source_uri"]

      - name: ingestion_errors
        description: "Row-level ingestion errors captured during parsing/loading."
        columns:
          - name: batch_id
            tests: [not_null]
          - name: dataset_name
            tests:
              - not_null
              - accepted_values:
                  values: ["drivers", "offers", "bookings"]
          - name: source_uri
            tests: [not_null]
          - name: error_type
            tests:
              - not_null
          - name: error_message
            tests: [not_null]
          - name: raw_record
          - name: created_at
            tests: [not_null]

      # -----------------------
      # Raw landing tables
      # -----------------------
      - name: raw_drivers
        description: "Raw landing table for freenow_drivers.csv (all columns as strings)."
        columns:
          - name: id
            tests: [not_null]
          - name: date_registration
          - name: driver_rating
          - name: rating_count
          - name: receive_marketing
          - name: country

          # ingestion metadata
          - name: _batch_id
            tests: [not_null]
          - name: _file_md5
            description: " "
            # tests: [not_null]
          - name: _source_uri
            tests: [not_null]
          - name: _ingested_at
            tests: [not_null]
          - name: _row_number
            tests: [not_null]

        tests:
          # Row uniqueness inside an ingestion file
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns: ["_batch_id", "_source_uri", "_row_number"]

      - name: raw_offers
        description: "Raw landing table for freenow_offers.csv (all columns as strings)."
        columns:
          - name: id
            tests: [not_null]
          - name: datecreated
            tests: [not_null]
          - name: bookingid
            tests: [not_null]
          - name: driverid
            tests: [not_null]
          - name: routedistance
          - name: state
            tests: [not_null]
          - name: driverread

          # ingestion metadata
          - name: _batch_id
            tests: [not_null]
          - name: _file_md5
            # tests: [not_null]
          - name: _source_uri
            tests: [not_null]
          - name: _ingested_at
            tests: [not_null]
          - name: _row_number
            tests: [not_null]

        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns: ["_batch_id", "_source_uri", "_row_number"]

      - name: raw_bookings
        description: "Raw landing table for freenow_bookings.csv (all columns as strings)."
        columns:
          - name: id
            tests: [not_null]
          - name: request_date
            tests: [not_null]
          - name: status
            tests: [not_null]
          - name: id_driver
          - name: estimated_route_fare

          # ingestion metadata
          - name: _batch_id
            tests: [not_null]
          - name: _file_md5
            # tests: [not_null]
          - name: _source_uri
            tests: [not_null]
          - name: _ingested_at
            tests: [not_null]
          - name: _row_number
            tests: [not_null]

        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns: ["_batch_id", "_source_uri", "_row_number"]